//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giffy.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseCodeString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseCodeString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Giffy.DataAccess.ResponseCodeString", typeof(ResponseCodeString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn tất..
        /// </summary>
        internal static string Action_Success {
            get {
                return ResourceManager.GetString("Action_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi trong quá trình tạo Comment..
        /// </summary>
        internal static string CommentCreate_Error {
            get {
                return ResourceManager.GetString("CommentCreate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn bạn đã đóng góp cho BONGVL.VN. Chúng tôi sẽ kiểm duyệt và công bố Gag này trong thời gian sớm nhất..
        /// </summary>
        internal static string GagCreate_Success {
            get {
                return ResourceManager.GetString("GagCreate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi trong quá trình tạo League..
        /// </summary>
        internal static string LeagueCreate_Error {
            get {
                return ResourceManager.GetString("LeagueCreate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo League thành công..
        /// </summary>
        internal static string LeagueCreate_Success {
            get {
                return ResourceManager.GetString("LeagueCreate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi trong quá trình tạo Like..
        /// </summary>
        internal static string LikeCreate_Error {
            get {
                return ResourceManager.GetString("LikeCreate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi trong quá trình tạo Player..
        /// </summary>
        internal static string PlayerCreate_Error {
            get {
                return ResourceManager.GetString("PlayerCreate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Player thành công..
        /// </summary>
        internal static string PlayerCreate_Success {
            get {
                return ResourceManager.GetString("PlayerCreate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi trong quá trình tạo Post..
        /// </summary>
        internal static string PostCreate_Error {
            get {
                return ResourceManager.GetString("PostCreate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xóa được Post do lỗi trong quá trình thực hiện..
        /// </summary>
        internal static string PostDelete_Error {
            get {
                return ResourceManager.GetString("PostDelete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy Post..
        /// </summary>
        internal static string PostGet_Error {
            get {
                return ResourceManager.GetString("PostGet_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi trong quá trình cập nhật Post..
        /// </summary>
        internal static string PostUpdate_Error {
            get {
                return ResourceManager.GetString("PostUpdate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi trong quá trình tạo Team..
        /// </summary>
        internal static string TeamCreate_Error {
            get {
                return ResourceManager.GetString("TeamCreate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Team thành công..
        /// </summary>
        internal static string TeamCreate_Success {
            get {
                return ResourceManager.GetString("TeamCreate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải đăng nhập để thực hiện hành động này..
        /// </summary>
        internal static string Unauthorized_Error {
            get {
                return ResourceManager.GetString("Unauthorized_Error", resourceCulture);
            }
        }
    }
}
